const menu = [
    {
      id: 1,
      title: 'hazy new england ipa',
      category: 'Ale',
      alcohol: "6.1%",
      price: 80,
      img: './images/1neipa.jpg',
      desc: `Keith Linn of Rogers, AR, member of the Fayetteville Lovers Of Pure Suds (FLOPS), won a gold medal in Category #19: New England IPA during the 2021 National Homebrew Competition. Linns New England IPA was chosen as first out of 191 entries in the category. `,
    },
    {
      id: 2,
      title: 'funkwerks saison',
      category: 'European',
      alcohol: "5.8%",
      price: 90,
      img: './images/2belgianale',
      desc: `Funkwerks Saison is the result of many backyard test batches, with the final recipe being a Great American Beer Festival-winning example of the classic Belgian-style saison. Expect some fruity character to accompany the yeast-driven spiciness. `,
    },
    {
      id: 3,
      title: 'the tropical session white ipa',
      category: 'Ale',
      alcohol: "4.8%",
      price: 85,
      img: './images/3tropicalsessionipa.jpg',
      desc: `This refreshing wheat beer has an IPA-level hopping that is sure to please palates of all kinds. Wheat beer sweetness paired with tropical fruit hops makes Beechums spin on a white session IPA a winner!`,
    },
    {
      id: 4,
      title: 'oktoberfest',
      category: 'Lager',
      alcohol: "4.5%",
      price: 90,
      img: './images/4oktoberfest.jpg',
      desc: `The original Oktoberfest celebrated the royal wedding of Crown Prince Ludwig I and Princess Therese in 1810, and they have been celebrating ever since (some beers are worth it). The hallmark of the Oktoberfest/Märzen style is a rich maltiness but high attenuation to make it less filling. If you plan to polka for 12 hours straight, then this is your beer.`,
    },
    {
      id: 5,
      title: 'knights dream',
      category: 'Ale',
      alcohol: "5.1%",
      price: 80,
      img: './images/5americanporter.jpg',
      desc: `Matt Knight of Milford, CT, member of the Brew Haven, won a gold medal in Category #14: American Porter & Stout with an American Porter during the 2019 National Homebrew Competition Final Round in Providence, RI with the help of Mike Joshi. Knight and Joshis American Porter & Stout was chosen as the best among 304 entries in the category.`,
    },
    {
      id: 6,
      title: 'chocolate beer',
      category: 'Ale',
      alcohol: "5.9%",
      price: 100,
      img: './images/chocolatebeer.jpg',
      desc: `Amahl Turczyn created this recipe based off of Mountain Sun Pub & Brewery's (Boulder, CO) chocolate stout; a staple during their annual Stout Month celebration every February. Expect lots of sweet chocolaty notes from the additions of lactose, dark and sweet chocolates.`,
    },
    {
      id: 7,
      title: 'irish red ale',
      category: 'Ale',
      alcohol: "5.6%",
      price: 80,
      img: './images/7irishredale.jpg',
      desc: `This is my standard Irish red ale. I enjoy the simplicity of using dry yeast and like the results I get from Nottingham yeast here. If you’d prefer to use liquid yeast, any of the Irish ale strains will work just fine, as would a clean American ale yeast. `,
    },
    {
      id: 8,
      title: 'kraken',
      category: 'European',
      alcohol: "7.9%",
      price: 120,
      img: './images/8kraken.jpg',
      desc: `Daniel Kukuk of Grosse Pointe, MI, won a gold medal in Category #26: Strong Belgian Ale with a Belgian Dark Strong Ale during the 2021 National Homebrew Competition. Kukuk’s Belgian Dark Strong Ale was chosen as first out of 246 entries in the category.`,
    },
    {
      id: 9,
      title: 'saisson',
      category: 'Ale',
      alcohol: "5.3%",
      price: 85,
      img: './images/9saisson.jpg',
      desc: `Little is known of the original yeast profile: the historical 60 to 63 percent attenuation seems poor to our eyes, but for its day, this beer was relatively well attenuated. A saison- or Brett-like profile seems appropriate, but to get that historical flavor, try to keep attenuation low by creating more unfermentable sugars in the mash. This helps simulate the fairly uncontrolled conditions that would have been found in a traditional Belgian brewery.`,
    },
  ];
  export default menu;